// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOkoWpRRw2Gun1JcXRaFOYedkRX46I-bs',
    appId: '1:497863850797:web:2f115f7a204c5f319bb1a4',
    messagingSenderId: '497863850797',
    projectId: 'myapp-6cf01',
    authDomain: 'myapp-6cf01.firebaseapp.com',
    storageBucket: 'myapp-6cf01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcT1hWpAtJEsiO2sUZGtYeybHREnEuh6I',
    appId: '1:497863850797:android:dca7ab37c9a55a929bb1a4',
    messagingSenderId: '497863850797',
    projectId: 'myapp-6cf01',
    storageBucket: 'myapp-6cf01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALrqtFcUgDkl3DQbOhy2JYaHKCNBlSnXM',
    appId: '1:497863850797:ios:672cca0f2569d42f9bb1a4',
    messagingSenderId: '497863850797',
    projectId: 'myapp-6cf01',
    storageBucket: 'myapp-6cf01.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALrqtFcUgDkl3DQbOhy2JYaHKCNBlSnXM',
    appId: '1:497863850797:ios:672cca0f2569d42f9bb1a4',
    messagingSenderId: '497863850797',
    projectId: 'myapp-6cf01',
    storageBucket: 'myapp-6cf01.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOkoWpRRw2Gun1JcXRaFOYedkRX46I-bs',
    appId: '1:497863850797:web:d76873d83bafe0b49bb1a4',
    messagingSenderId: '497863850797',
    projectId: 'myapp-6cf01',
    authDomain: 'myapp-6cf01.firebaseapp.com',
    storageBucket: 'myapp-6cf01.firebasestorage.app',
  );

}